matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      addons:
        apt:
          packages:
            - pyqt4-dev-tools
            - python-qt4
      before_install:
        - cp -r $(dirname $(python -c 'import PyQt4; print(PyQt4.__file__)')) ~/virtualenv/python2.7/lib/python2.7/site-packages/
        - cp $(python -c 'import sip; print(sip.__file__)') ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - os: osx
      osx_image: xcode8
      language: generic
      before_install:
        - brew install qt qt4
    - os: osx
      osx_image: xcode9
      language: generic
      before_install:
        - brew install pyqt --with-python

install:
  - python setup.py install

before_script:
  - pip install nose

script:
  - nosetests tests
