sudo: false

cache: pip

matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      env:
        - SYSTEM_PYTHON=/usr/bin/python
        - PIP=pip
        - PYTHON=python
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
            - pyqt4-dev-tools
            - python-qt4
      before_install:
        - cp -r $(dirname $($SYSTEM_PYTHON -c 'import PyQt4; print(PyQt4.__file__)')) ~/virtualenv/python2.7/lib/python2.7/site-packages/
        - cp $($SYSTEM_PYTHON -c 'import sip; print(sip.__file__)') ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - os: osx
      osx_image: xcode9
      language: generic
      env:
        - PIP=/usr/local/opt/python/libexec/bin/pip
        - PYTHON=/usr/local/opt/python/libexec/bin/python
      before_install:
        - brew install pyqt

install:
  - $PIP install -U pip setuptools
  - $PIP install -U numpy  # for scikit-image
  - $PYTHON setup.py install

before_script:
  - $PIP install nose

script:
  - nosetests tests
