matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      addons:
        apt:
          packages:
            - pyqt4-dev-tools
            - python-qt4
    - os: osx
      osx_image: xcode8
      language: generic
      before_install:
        - brew install qt qt4
    - os: osx
      osx_image: xcode9
      language: generic
      before_install:
        - brew install pyqt --with-python

install:
  - python setup.py install

before_script:
  - pip install nose

script:
  - nosetests tests
